version: '3.8'

services:
  backend:
    image: ghcr.io/jornpe/water-temp-backend:latest
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - PORT=8080
    ports:
      - "8080:8080"

  frontend:
    image: ghcr.io/jornpe/water-temp-frontend:latest
    # Provide full backend URL for the frontend to reach the API
    # Override via env when running compose: API_BASE_URL=https://api.example.com
    environment:
      - API_BASE_URL=${API_BASE_URL:-http://backend:8080}
    depends_on:
      - backend
    ports:
      - "80:80"
