version: '3.8'

services:
  backend:
    image: ghcr.io/jornpe/water-temp-backend:latest
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - PORT=8080
    ports:
      - "8080:8080"

  frontend:
    image: ghcr.io/jornpe/water-temp-frontend:latest
    environment:
      # If the frontend is built with a static base, this can be empty.
      # Build-time arg VITE_API_BASE_URL should be set to your backend URL.
      - NGINX_PORT=80
      - VITE_API_BASE_URL=http://backend:8080
    depends_on:
      - backend
    ports:
      - "80:80"
