version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: src/backend/WaterTemperature.Api/Dockerfile
    image: water-temp/backend:local
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - PORT=8080
    ports:
      - "8080:8080"

  frontend:
    build:
      context: ./src/frontend/app
      dockerfile: Dockerfile
    image: water-temp/frontend:local
    environment:
      # Full backend URL for Nginx to proxy to (override as needed)
      - API_BASE_URL=http://backend:8080
    depends_on:
      - backend
    ports:
      - "5173:80"
    # If you host behind reverse proxy, change published port accordingly
