// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using WaterTemperature.Api.Data;

#nullable disable

namespace WaterTemperature.Api.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260801144151_CalculateBatteryPercentageFromAdc")]
    partial class CalculateBatteryPercentageFromAdc
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("WaterTemperature.Api.Data.Device", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("ApiKeyCreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ApiKeyHash")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<DateTime?>("ApiKeyIssuedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("ApiKeyLastUsedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<float>("BatteryEmptyAdcVoltage")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("real")
                        .HasDefaultValue(2.5f);

                    b.Property<float>("BatteryFullAdcVoltage")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("real")
                        .HasDefaultValue(4.2f);

                    b.Property<int>("ConfigurationSyncAttemptCount")
                        .HasColumnType("integer");

                    b.Property<string>("ConfigurationSyncError")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<string>("ConfigurationSyncStatus")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<DateTime?>("ConfigurationSyncStatusUpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DesiredConfigurationUpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("DesiredConfigurationVersion")
                        .HasColumnType("integer");

                    b.Property<string>("DeviceIdentifier")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("FirmwareVersion")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("HomeAssistantDeviceName")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime?>("LastDiscoveredAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("LastDiscoveryTransport")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<DateTime?>("LastSeenAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("LastUpdateReceivedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<double?>("LatestAltitudeMeters")
                        .HasColumnType("double precision");

                    b.Property<float?>("LatestBatteryAdcVoltage")
                        .HasColumnType("real");

                    b.Property<DateTime?>("LatestBatteryAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("LatestBatteryChargeState")
                        .HasColumnType("integer");

                    b.Property<int?>("LatestBatteryModemMillivolts")
                        .HasColumnType("integer");

                    b.Property<bool?>("LatestBatteryModemReadingValid")
                        .HasColumnType("boolean");

                    b.Property<string>("LatestBatteryState")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<bool?>("LatestCellularGprsConnected")
                        .HasColumnType("boolean");

                    b.Property<string>("LatestCellularLocalIp")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<bool?>("LatestCellularNetworkConnected")
                        .HasColumnType("boolean");

                    b.Property<string>("LatestCellularOperator")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<int?>("LatestCellularSignalQuality")
                        .HasColumnType("integer");

                    b.Property<string>("LatestCellularSimStatus")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<DateTime?>("LatestGpsTimeUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<double?>("LatestHdop")
                        .HasColumnType("double precision");

                    b.Property<double?>("LatestLatitude")
                        .HasColumnType("double precision");

                    b.Property<double?>("LatestLongitude")
                        .HasColumnType("double precision");

                    b.Property<string>("LatestNetworkTransport")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<DateTime?>("LatestPositionAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("LatestSatellitesUsed")
                        .HasColumnType("integer");

                    b.Property<int?>("LatestSatellitesVisible")
                        .HasColumnType("integer");

                    b.Property<double?>("LatestSpeedKnots")
                        .HasColumnType("double precision");

                    b.Property<DateTime?>("LatestTemperatureAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal?>("LatestTemperatureCelsius")
                        .HasColumnType("numeric");

                    b.Property<string>("LatestWifiBssid")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<int?>("LatestWifiChannel")
                        .HasColumnType("integer");

                    b.Property<string>("LatestWifiDnsIp")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("LatestWifiGatewayIp")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("LatestWifiLocalIp")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("LatestWifiMacAddress")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<int?>("LatestWifiRssiDbm")
                        .HasColumnType("integer");

                    b.Property<string>("LatestWifiSsid")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("LatestWifiSubnetMask")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("Name")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("PendingApiKeyProtected")
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)");

                    b.Property<string>("Place")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<bool>("PushToHomeAssistant")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("RegisteredAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("ReportIntervalSeconds")
                        .HasColumnType("integer");

                    b.Property<int?>("ReportedConfigurationVersion")
                        .HasColumnType("integer");

                    b.Property<int?>("ReportedReportIntervalSeconds")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("RuntimeConfigurationReportedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.HasKey("Id");

                    b.HasIndex("DeviceIdentifier")
                        .IsUnique();

                    b.ToTable("Devices", t =>
                        {
                            t.HasCheckConstraint("CK_Devices_BatteryAdcVoltageRange", "\"BatteryEmptyAdcVoltage\" >= 0 AND \"BatteryFullAdcVoltage\" > \"BatteryEmptyAdcVoltage\"");
                        });
                });

            modelBuilder.Entity("WaterTemperature.Api.Data.DeviceBatteryHistory", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<float>("AdcVoltage")
                        .HasColumnType("real");

                    b.Property<string>("BatteryState")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<int>("ChargeState")
                        .HasColumnType("integer");

                    b.Property<int>("DeviceId")
                        .HasColumnType("integer");

                    b.Property<int>("ModemMillivolts")
                        .HasColumnType("integer");

                    b.Property<bool>("ModemReadingValid")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("RecordedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("DeviceId", "RecordedAtUtc");

                    b.ToTable("DeviceBatteryHistory");
                });

            modelBuilder.Entity("WaterTemperature.Api.Data.DeviceLogEntry", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("DeviceId")
                        .HasColumnType("integer");

                    b.Property<string>("Level")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)");

                    b.Property<DateTime>("TimestampUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("DeviceId", "Id");

                    b.HasIndex("DeviceId", "Level", "Id");

                    b.HasIndex("DeviceId", "TimestampUtc", "Id");

                    b.ToTable("DeviceLogEntries");
                });

            modelBuilder.Entity("WaterTemperature.Api.Data.DevicePositionHistory", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<double?>("AltitudeMeters")
                        .HasColumnType("double precision");

                    b.Property<int>("DeviceId")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("GpsTimeUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<double?>("Hdop")
                        .HasColumnType("double precision");

                    b.Property<double>("Latitude")
                        .HasColumnType("double precision");

                    b.Property<double>("Longitude")
                        .HasColumnType("double precision");

                    b.Property<DateTime>("RecordedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("SatellitesUsed")
                        .HasColumnType("integer");

                    b.Property<int?>("SatellitesVisible")
                        .HasColumnType("integer");

                    b.Property<double?>("SpeedKnots")
                        .HasColumnType("double precision");

                    b.HasKey("Id");

                    b.HasIndex("DeviceId", "RecordedAtUtc");

                    b.ToTable("DevicePositionHistory");
                });

            modelBuilder.Entity("WaterTemperature.Api.Data.DeviceTemperatureHistory", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<int>("DeviceId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("RecordedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("TemperatureCelsius")
                        .HasPrecision(6, 2)
                        .HasColumnType("numeric(6,2)");

                    b.HasKey("Id");

                    b.HasIndex("DeviceId", "RecordedAtUtc");

                    b.ToTable("DeviceTemperatureHistory");
                });

            modelBuilder.Entity("WaterTemperature.Api.Data.HomeAssistantIntegrationSettings", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("integer");

                    b.Property<bool>("Enabled")
                        .HasColumnType("boolean");

                    b.Property<string>("Host")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("Password")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<int>("Port")
                        .HasColumnType("integer");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Username")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.HasKey("Id");

                    b.ToTable("HomeAssistantIntegrationSettings", t =>
                        {
                            t.HasCheckConstraint("CK_HomeAssistantIntegrationSettings_Singleton", "\"Id\" = 1");
                        });
                });

            modelBuilder.Entity("WaterTemperature.Api.Data.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("FirstName")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<bool>("IsAdmin")
                        .HasColumnType("boolean");

                    b.Property<string>("LastName")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<byte[]>("ProfilePicture")
                        .HasColumnType("bytea");

                    b.Property<string>("ProfilePictureContentType")
                        .HasColumnType("text");

                    b.Property<string>("RefreshToken")
                        .HasColumnType("text");

                    b.Property<DateTime?>("RefreshTokenExpiry")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("WaterTemperature.Api.Data.DeviceBatteryHistory", b =>
                {
                    b.HasOne("WaterTemperature.Api.Data.Device", "Device")
                        .WithMany("BatteryHistory")
                        .HasForeignKey("DeviceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Device");
                });

            modelBuilder.Entity("WaterTemperature.Api.Data.DeviceLogEntry", b =>
                {
                    b.HasOne("WaterTemperature.Api.Data.Device", "Device")
                        .WithMany("LogEntries")
                        .HasForeignKey("DeviceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Device");
                });

            modelBuilder.Entity("WaterTemperature.Api.Data.DevicePositionHistory", b =>
                {
                    b.HasOne("WaterTemperature.Api.Data.Device", "Device")
                        .WithMany("PositionHistory")
                        .HasForeignKey("DeviceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Device");
                });

            modelBuilder.Entity("WaterTemperature.Api.Data.DeviceTemperatureHistory", b =>
                {
                    b.HasOne("WaterTemperature.Api.Data.Device", "Device")
                        .WithMany("TemperatureHistory")
                        .HasForeignKey("DeviceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Device");
                });

            modelBuilder.Entity("WaterTemperature.Api.Data.Device", b =>
                {
                    b.Navigation("BatteryHistory");

                    b.Navigation("LogEntries");

                    b.Navigation("PositionHistory");

                    b.Navigation("TemperatureHistory");
                });
#pragma warning restore 612, 618
        }
    }
}
