name: ci

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-backend:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: src/backend/WaterTemperature.Api
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.0.x'
      - name: Restore
        run: dotnet restore
      - name: Build
        run: dotnet build --configuration Release --no-restore
      - name: Publish
        run: dotnet publish -c Release -o out --no-build /p:UseAppHost=false

  test-backend:
    runs-on: ubuntu-latest
    needs: build-backend
    defaults:
      run:
        working-directory: src/backend/WaterTemperature.Api.Tests
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.0.x'
      - name: Restore
        run: dotnet restore
      - name: Test
        run: dotnet test -c Release --no-restore --logger "trx;LogFileName=test-results.trx"
      - name: Publish Test Results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: backend-test-results
          path: src/backend/WaterTemperature.Api.Tests/TestResults

  build-frontend:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: src/frontend/app
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'
          cache-dependency-path: 'src/frontend/app/package-lock.json'
      - name: Install
        run: |
          if [ -f package-lock.json ]; then npm ci; else npm i; fi
      - name: Build
        run: npm run build

  docker-images:
    runs-on: ubuntu-latest
    needs: [build-backend, build-frontend, test-backend]
    steps:
      - uses: actions/checkout@v4
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to GHCR
        if: github.ref == 'refs/heads/main'
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build backend image
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./src/backend/WaterTemperature.Api/Dockerfile
          push: ${{ github.ref == 'refs/heads/main' }}
          tags: |
            ghcr.io/jornpe/water-temp-backend:latest
            ghcr.io/jornpe/water-temp-backend:${{ github.sha }}
      - name: Build frontend image
        uses: docker/build-push-action@v6
        with:
          context: ./src/frontend/app
          file: ./src/frontend/app/Dockerfile
          build-args: |
            VITE_API_BASE_URL=${{ vars.FRONTEND_BUILD_API_BASE_URL || '/api' }}
          push: ${{ github.ref == 'refs/heads/main' }}
          tags: |
            ghcr.io/jornpe/water-temp-frontend:latest
            ghcr.io/jornpe/water-temp-frontend:${{ github.sha }}
